# Generated by Django 5.1.4 on 2024-12-29 16:17

import django.db.models.deletion
import django_extensions.db.fields
import django_uuid_upload
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business_description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_name',
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('user', 'user'), ('property_owner', 'property_owner')], default='user', max_length=60),
        ),
        migrations.CreateModel(
            name='UserBusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('business_name', models.CharField(max_length=255)),
                ('business_description', models.TextField()),
                ('business_logo', models.ImageField(blank=True, null=True, upload_to=functools.partial(django_uuid_upload._upload_to_uuid_impl, *(), **{'make_dir': False, 'path': 'business_logos/', 'remove_qs': True}))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Business Profile',
                'verbose_name_plural': 'User Business Profiles',
            },
        ),
    ]
