# Generated by Django 5.1.4 on 2024-12-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_remove_user_business_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbusinessprofile',
            name='business_location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbusinessprofile',
            name='business_website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userbusinessprofile',
            name='total_ratings',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userbusinessprofile',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('freelancer', 'freelancer'), ('property_owner', 'property_owner')], default='freelancer', max_length=60),
        ),
    ]
