# Generated by Django 5.1.4 on 2025-01-06 05:42

import django.utils.timezone
import django_uuid_upload
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_userbusinessprofile_business_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbusinessprofile',
            options={'verbose_name': "Profil d'entreprise", 'verbose_name_plural': "Profils d'entreprise"},
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('freelancer', 'freelancer'), ('property_owner', 'property_owner')], default='freelancer', max_length=60, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='normalized_email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Normalized Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(django_uuid_upload._upload_to_uuid_impl, *(), **{'make_dir': False, 'path': 'profile_photos/', 'remove_qs': True}), verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sign_up_with',
            field=models.CharField(default='email', max_length=60, verbose_name='Sign Up With'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_expiry',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Token Expiry'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, null=True, verbose_name='Username'),
        ),
    ]
