# Generated by Django 5.1.4 on 2025-01-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0005_user_profession_userbusinessprofile_workspace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('Freelancer', 'Freelancer'), ('Owner', 'Owner')], default='Freelancer', max_length=60, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='normalized_email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Normalized Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Username'),
        ),
    ]
