# Generated by Django 5.1.4 on 2025-01-10 07:43

import django_uuid_upload
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0006_alter_user_account_type_alter_user_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbusinessprofile',
            options={'verbose_name': 'Profil du propriétaire', 'verbose_name_plural': 'Profils de propriétaires'},
        ),
        migrations.AddField(
            model_name='userbusinessprofile',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='notation'),
        ),
        migrations.AlterField(
            model_name='userbusinessprofile',
            name='business_description',
            field=models.TextField(verbose_name="Description de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='userbusinessprofile',
            name='business_location',
            field=models.CharField(max_length=255, verbose_name="Emplacement de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='userbusinessprofile',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(django_uuid_upload._upload_to_uuid_impl, *(), **{'make_dir': False, 'path': 'business_logos/', 'remove_qs': True}), verbose_name="Logo d'entreprise"),
        ),
        migrations.AlterField(
            model_name='userbusinessprofile',
            name='business_name',
            field=models.CharField(max_length=255, verbose_name="Nom de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='userbusinessprofile',
            name='business_website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name="Site Web d'entreprise"),
        ),
        migrations.AlterField(
            model_name='userbusinessprofile',
            name='total_ratings',
            field=models.FloatField(default=0.0, verbose_name='Note totale'),
        ),
        migrations.AlterField(
            model_name='userbusinessprofile',
            name='total_reviews',
            field=models.IntegerField(default=0, verbose_name='Total des avis'),
        ),
        migrations.AlterField(
            model_name='userbusinessprofile',
            name='workspace',
            field=models.CharField(max_length=255, verbose_name='Espace de travail'),
        ),
    ]
