# Generated by Django 5.1.4 on 2025-01-10 12:44

import django_uuid_upload
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0007_alter_userbusinessprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbusinessprofile',
            name='business_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail de contact'),
        ),
        migrations.AddField(
            model_name='userbusinessprofile',
            name='phone_number',
            field=models.CharField(default=1, max_length=150, verbose_name='Numéro de contact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('Freelancer', 'Freelancer'), ('Owner', 'Owner')], default='Freelancer', max_length=60, verbose_name='Type de compte'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom et prénom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, verbose_name='Mot de passe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de contact'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(django_uuid_upload._upload_to_uuid_impl, *(), **{'make_dir': False, 'path': 'profile_photos/', 'remove_qs': True}), verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sign_up_with',
            field=models.CharField(default='email', max_length=60, verbose_name='Inscrivez-vous avec'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Nom d'utilisateur"),
        ),
    ]
