# Generated by Django 5.1.4 on 2025-01-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0008_userbusinessprofile_business_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbusinessprofile',
            name='business_description',
        ),
        migrations.RemoveField(
            model_name='userbusinessprofile',
            name='business_location',
        ),
        migrations.AddField(
            model_name='userbusinessprofile',
            name='description',
            field=models.TextField(default=1, verbose_name='Description ou détails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbusinessprofile',
            name='location',
            field=models.CharField(default=1, max_length=255, verbose_name='emplacement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userbusinessprofile',
            name='business_website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Site Web'),
        ),
    ]
