# Generated by Django 5.1.4 on 2024-12-30 12:35

import django.db.models.deletion
import django_extensions.db.fields
import django_uuid_upload
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auths', '0003_userbusinessprofile_business_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdListImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('image', models.ImageField(upload_to=functools.partial(django_uuid_upload._upload_to_uuid_impl, *(), **{'make_dir': False, 'path': 'ad_listing/images/', 'remove_qs': True}))),
            ],
            options={
                'verbose_name': 'Ad List Image',
                'verbose_name_plural': 'Ad List Images',
            },
        ),
        migrations.CreateModel(
            name='AdListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('space_type', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('availability', models.CharField(max_length=300)),
                ('rental_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_ratings', models.FloatField(default=0.0)),
                ('ad_list_images', models.ManyToManyField(to='ad_listing.adlistimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_user', to='auths.userbusinessprofile')),
            ],
            options={
                'verbose_name': 'Ad Listing',
                'verbose_name_plural': 'Ad Listings',
            },
        ),
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=300)),
                ('is_review', models.BooleanField(default=False)),
                ('ad_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_listing_rental_requests', to='ad_listing.adlisting')),
                ('rental_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rental Request',
                'verbose_name_plural': 'Rental Requests',
            },
        ),
        migrations.CreateModel(
            name='AdReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('rating', models.IntegerField(default=0)),
                ('feedback', models.TextField()),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='auths.userbusinessprofile')),
                ('review_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to=settings.AUTH_USER_MODEL)),
                ('user_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_request', to='ad_listing.rentalrequest')),
            ],
            options={
                'verbose_name': 'Ad Review',
                'verbose_name_plural': 'Ad Reviews',
            },
        ),
    ]
