# Generated by Django 5.1.4 on 2024-12-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_listing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adlisting',
            name='ad_list_images',
        ),
        migrations.AddField(
            model_name='adlisting',
            name='ad_images',
            field=models.ManyToManyField(blank=True, related_name='ad_list_images', to='ad_listing.adlistimage'),
        ),
    ]
