# Generated by Django 5.1.4 on 2025-01-01 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_listing', '0002_remove_adlisting_ad_list_images_adlisting_ad_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adreview',
            name='owner_user',
        ),
    ]
