# Generated by Django 5.1.4 on 2025-01-06 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_listing', '0003_remove_adreview_owner_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adlistimage',
            options={'verbose_name': 'Annonces-Image', 'verbose_name_plural': 'Annonces-Images'},
        ),
        migrations.AlterModelOptions(
            name='adlisting',
            options={'verbose_name': 'Liste des annonces', 'verbose_name_plural': 'Annonces'},
        ),
        migrations.AlterModelOptions(
            name='adreview',
            options={'verbose_name': 'Examen des annonces', 'verbose_name_plural': 'Examens des annonces'},
        ),
        migrations.AlterModelOptions(
            name='rentalrequest',
            options={'verbose_name': 'Demande de location', 'verbose_name_plural': 'Demandes de location'},
        ),
    ]
