# Generated by Django 5.1.4 on 2025-01-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_listing', '0005_alter_adlistimage_options_alter_adlisting_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='adlisting',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
